server:
  port: ${SERVER_PORT:9220}

spring:
  sleuth:
    sampler:
      probability: ${SLEUTH_SAMPLER_PROBABILITY:1.0}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:none}

datasource:
  master:
    url: ${MASTER_DB_URL}
    username: ${MASTER_DB_USERNAME}
    password: ${MASTER_DB_PASSWORD}
    maximum-pool-size: ${MASTER_DB_MAX_POOL_SIZE:50}
    minimum-idle: ${MASTER_DB_MIN_IDLE:10}
    connection-timeout: ${MASTER_DB_CONN_TIMEOUT:30000}
    idle-timeout: ${MASTER_DB_IDLE_TIMEOUT:600000}
    max-lifetime: ${MASTER_DB_MAX_LIFETIME:1800000}
    pool-name: ${MASTER_DB_POOL_NAME:UserMasterHikariCP}
    validation-timeout: ${MASTER_DB_VALIDATION_TIMEOUT:5000}
    leak-detection-threshold: ${MASTER_DB_LEAK_DETECTION_THRESHOLD:60000}
  slave:
    url: ${SLAVE_DB_URL}
    username: ${SLAVE_DB_USERNAME}
    password: ${SLAVE_DB_PASSWORD}
    maximum-pool-size: ${SLAVE_DB_MAX_POOL_SIZE:50}
    minimum-idle: ${SLAVE_DB_MIN_IDLE:10}
    connection-timeout: ${SLAVE_DB_CONN_TIMEOUT:30000}
    idle-timeout: ${SLAVE_DB_IDLE_TIMEOUT:600000}
    max-lifetime: ${SLAVE_DB_MAX_LIFETIME:1800000}
    pool-name: ${SLAVE_DB_POOL_NAME:UserSlaveHikariCP}
    validation-timeout: ${SLAVE_DB_VALIDATION_TIMEOUT:5000}
    leak-detection-threshold: ${SLAVE_DB_LEAK_DETECTION_THRESHOLD:60000}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD}
  database:
    index: ${REDIS_DB_INDEX:0}
  pool:
    max:
      connection: ${REDIS_POOL_MAX_CONN:30}
      idle:
        connection: ${REDIS_POOL_MAX_IDLE_CONN:10}
    min:
      idle:
        connection: ${REDIS_POOL_MIN_IDLE_CONN:0}

logging:
  config: ${LOGGING_CONFIG:classpath:log/logback-k8s.xml}

services:
  payment:
    base-url: ${PAYMENT_SERVICE_BASE_URL:http://localhost:9014}
  remittance:
    base-url: ${REMITTANCE_SERVICE_BASE_URL:localhost:90}
