server:
  port: 0
  shutdown: graceful

log:
  dir: skeleton

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{correlationId:-}]"

info:
  app:
    name: Customer Service
    description: This service is responsible for Customer.
    version: 1.0

spring:
  profiles:
    active: dev
  application:
    name: skeleton-service
  lifecycle:
    timeout-per-shutdown-phase: "90s"
  jpa:
    database-platform: postgres
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true
  main:
    allow-bean-definition-overriding: true
  cloud:
    kubernetes:
      loadbalancer:
        mode: service
      discovery:
        all-namespaces: false
        namespaces:
          - skeleton

springdoc:
  paths-to-exclude: /swagger-resources/**, /v3/api-docs/**, /v2/api-docs/**


