server:
  port: 0
  shutdown: graceful

log:
  dir: skeleton

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{correlationId:-}]"

info:
  app:
    name: User Service
    description: This service is responsible for Customer.
    version: 1.0

spring:
  profiles:
    active: test
  application:
    name: user-service
  lifecycle:
    timeout-per-shutdown-phase: "90s"
  jpa:
    database-platform: postgres
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true
  main:
    allow-bean-definition-overriding: true
  cloud:
    kubernetes:
      loadbalancer:
        mode: service
      discovery:
        all-namespaces: false
        namespaces:
          - user
  mail:
    host: smtp.gmail.com
    port: 587
    username: shahinbeg80@gmail.com
    password: zstnslhqoiprmdmh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  paths-to-exclude: /swagger-resources/**, /v3/api-docs/**, /v2/api-docs/**

jwt:
  token:
    expiry:
      minute: 30
    live:
      minute: 60
    prefix: Bearer
  secret:
    key: SzdmR3R5eTlOd1NnVzU0QUFiaFhSUk1rNEJtcXd6U3Z5ckgyOHl6M1NqWWF5Ymp4cXZ0RzNyVzc0WldXNHVoZFB2UGVTRVJjeHpWUjd2RHVKelA5emFSSHBCOFQ1cFBydnJwN1ZRVUZEeGtNU20yOHEyY05Wa0U1bmFxcmhld20=
  id-token:
    secret:
      key: Y3k0U0I1Mnd2YkZLY1I0OXB2VW1NN0dyUjNFcWFuQTdxeTJ3Tjh3ejVQUFp4OXFWa2R2V0p5VFN6cHhqckRtTTh0anJXemt0dTdnUXpTdjJicXlQOFZ2bURCclc0YWVBTlJIWXJraEc0U2hwYVZXM2U1eFBYSFJFN1N5ZlJ6dWg=

payload:
  encryption:
    secret:
      key: 3XT3RN@L_P@YL0@D_S3CR3T
feign:
  client:
    config:
      default:
        ribbon:
          enabled: false

cbs:
  eq-connection:
    token:
      ttl-in-minutes: ${CBS_EQ_COMMONWS_TOKEN_IN_MIN:240}
